// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoaqQboMy4XXXiQt7NpPAvy1ev_gA_Ps4',
    appId: '1:270287139745:web:a6140cb07d30756be391e0',
    messagingSenderId: '270287139745',
    projectId: 'lmslegend-87688',
    authDomain: 'lmslegend-87688.firebaseapp.com',
    storageBucket: 'lmslegend-87688.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_gAZ6IfUnmhzD6XIlJ1476Hk85B3JfrY',
    appId: '1:270287139745:android:dff148edd57d55c2e391e0',
    messagingSenderId: '270287139745',
    projectId: 'lmslegend-87688',
    storageBucket: 'lmslegend-87688.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJCPcTTRlPXzljI-EBsG1paDVyvPZcfu0',
    appId: '1:270287139745:ios:1c48bbdc514b981be391e0',
    messagingSenderId: '270287139745',
    projectId: 'lmslegend-87688',
    storageBucket: 'lmslegend-87688.firebasestorage.app',
    iosBundleId: 'com.example.lsmLegends',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJCPcTTRlPXzljI-EBsG1paDVyvPZcfu0',
    appId: '1:270287139745:ios:1c48bbdc514b981be391e0',
    messagingSenderId: '270287139745',
    projectId: 'lmslegend-87688',
    storageBucket: 'lmslegend-87688.firebasestorage.app',
    iosBundleId: 'com.example.lsmLegends',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoaqQboMy4XXXiQt7NpPAvy1ev_gA_Ps4',
    appId: '1:270287139745:web:d45ab5d5391c6573e391e0',
    messagingSenderId: '270287139745',
    projectId: 'lmslegend-87688',
    authDomain: 'lmslegend-87688.firebaseapp.com',
    storageBucket: 'lmslegend-87688.firebasestorage.app',
  );
}
